apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-pvc
  namespace: influx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-influx-sc
  resources:
    requests:
      storage: 20Gi
      