apiVersion: v1
kind: Service
metadata:
  name: influxdb2-svc
  namespace: influx
  labels:
    app.kubernetes.io/name: influxdb2
    app.kubernetes.io/instance: influx
    app.kubernetes.io/version: "2.7.4"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: influxdb2-2.1.2
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8086
  selector:
    app.kubernetes.io/name: influxdb2
    app.kubernetes.io/instance: influx