services:
  prefect-worker:
    image: prefecthq/prefect:3.3.5-python3.11
    container_name: prefect-worker
    tty: true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # DooD (Docker out of Docker)
      - ./entrypoint.py:/entrypoint.py
    env_file:
      - prefect-worker.env
    command: >
      python3 /entrypoint.py