apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: node-cpu-train
spec:
  template:
    metadata:
      labels:
        node-pool: node-cpu-train
        ray/type: train-cpu
    spec:
      requirements:
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["us-west-2a"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["4"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: node-cpu-train
      expireAfter: 720h # 30 * 24h = 720h
      taints:
        - key: ray/train-cpu
          value: "true"
          effect: NoSchedule
  limits:
    cpu: 640
    # memory: 256Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 1m