apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: node-cpu-train
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: ${node_iam_role_name} # replace with your cluster name
  tags:
    node-class: node-cpu-train
    Name: eks-${cluster_name}-cpu
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${cluster_name} # replace with your cluster name
        Name: ${cluster_name}-private-us-west-2a
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${cluster_name} # replace with your cluster name
  amiSelectorTerms:
    - id: "ami-091afad7b258598e7"
  blockDeviceMappings:
    - deviceName: "/dev/xvda"       # 루트 볼륨 장치 이름
      ebs:
        volumeSize: 100Gi           # EBS 볼륨 크기를 100GiB로 설정
        volumeType: gp3             # 볼륨 유형 (gp3, gp2 등)
        iops: 125
        throughput: 125
        deleteOnTermination: true   # 인스턴스 종료 시 볼륨 삭제