apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: infra
data:
  nginx.conf: |
    events { }
    http {
        server {
            listen 80;
            server_name infra.aipixell.com;

            location /mlflow/ {
                proxy_pass http://mlflow-service.infra.svc.cluster.local:5000/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            location /n8n/ {
                proxy_pass http://n8n-svc.infra.svc.cluster.local:5678/;
                    
                # WebSocket 지원 설정
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                
                # 기본 헤더 설정
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                # 버퍼링 및 캐싱 비활성화
                proxy_buffering off;
                proxy_cache off;
                chunked_transfer_encoding off;
                
                # 시간 초과 설정
                proxy_read_timeout 360s;
                proxy_send_timeout 360s;
            }
        }
    }

