apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: infra
data:
  nginx.conf: |
    events { }
    http {
        server {
            listen 80;
            server_name infra.aipixell.com;

            location /mlflow/ {
                proxy_pass http://mlflow-service.infra.svc.cluster.local:5000/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }
    }