apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: node-cpu
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["4"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: node-cpu
      expireAfter: 720h # 30 * 24h = 720h
  limits:
    cpu: 64
    # memory: 256Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 1m