apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: node-gpu
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["g"]
        - key: karpenter.k8s.aws/instance-generation
          operator: In
          values: ["5"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: node-gpu
      expireAfter: 720h # 30 * 24h = 720h
      taints:
        - key: nvidia.com/gpu
          value: "true"
          effect: NoSchedule  # GPU가 필요하지 않은 Pod는 이 노드에 스케줄링되지 않음
  limits:
    cpu: 2000
    # memory: 3840Gi
    # nvidia.com/gpu: "40"
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 1m