apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deploy: n8n
  name: n8n-deploy
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: n8n
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          securityContext:
            runAsUser: 50000
            runAsGroup: 50000
          command: ["sh", "-c", "mkdir -p /efs/n8n"]
          volumeMounts:
            - name: n8n-pv
              mountPath: /efs
      containers:
        - command:
            - /bin/sh
          securityContext:
            runAsUser: 50000
            runAsGroup: 50000
          args:
            - -c
            - sleep 5; n8n start
          env:
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_HOST
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: POSTGRES_HOST
            - name: DB_POSTGRESDB_PORT
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: POSTGRES_PORT
            - name: DB_POSTGRESDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: POSTGRES_N8N_DATABASE
            - name: N8N_USER_FOLDER
              value: /data
            - name: N8N_SECURE_COOKIE
              value: "false"
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: POSTGRES_USERNAME
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: POSTGRES_PASSWORD
            - name: N8N_PATH
              value: /n8n/
            - name: N8N_PROTOCOL
              value: https
            - name: N8N_HOST
              value: infra.aipixell.com
            - name: N8N_PORT
              value: "5678"
          image: n8nio/n8n
          name: n8n
          ports:
            - containerPort: 5678
          resources:
            requests:
              memory: "250Mi"
            limits:
              memory: "500Mi"
          volumeMounts:
            - mountPath: /data
              name: n8n-pv
              subPath: n8n
      restartPolicy: Always
      volumes:
        - name: n8n-pv
          persistentVolumeClaim:
            claimName: n8n-pvc
        - name: n8n-secret
          secret:
            secretName: n8n-secret
        - name: infra-secrets
          secret:
            secretName: infra-secrets