apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deploy: n8n-pg
  name: n8n-pg-deploy
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n-pg
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: n8n-pg
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          securityContext:
            runAsUser: 50000
            runAsGroup: 50000
          command: ["sh", "-c", "mkdir -p /efs/postgresql"]
          volumeMounts:
            - name: postgresql-pv
              mountPath: /efs
      containers:
        - image: postgres:11
          securityContext:
            runAsUser: 50000
            runAsGroup: 50000
          name: postgres
          resources:
            limits:
              cpu: "4"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 2Gi
          volumeMounts:
            - name: init-data
              mountPath: /docker-entrypoint-initdb.d/init-n8n-user.sh
              subPath: init-data.sh
            - name: postgresql-pv
              mountPath: /efs
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /efs/postgresql   
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: N8N_POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: N8N_POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: n8n
            - name: POSTGRES_NON_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: N8N_POSTGRES_NON_ROOT_USER
            - name: POSTGRES_NON_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: N8N_POSTGRES_NON_ROOT_PASSWORD
            - name:   POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_PORT
              value: '5432'
      restartPolicy: Always
      volumes:
        - name: postgresql-pv
          persistentVolumeClaim:
            claimName: n8n-pvc
        - name: infra-secrets
          secret:
            secretName: infra-secrets
        - name: init-data
          configMap:
            name: init-data
            defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deploy: n8n
  name: n8n-deploy
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: n8n
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          securityContext:
            runAsUser: 50000
            runAsGroup: 50000
          command: ["sh", "-c", "mkdir -p /efs/n8n"]
          volumeMounts:
            - name: n8n-pv
              mountPath: /efs
      containers:
        - command:
            - /bin/sh
          securityContext:
            runAsUser: 50000
            runAsGroup: 50000
          args:
            - -c
            - sleep 5; n8n start
          env:
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_HOST
              value: n8n-pg-svc.infra.svc.cluster.local
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_DATABASE
              value: n8n
            - name: N8N_USER_FOLDER
              value: /data
            - name: N8N_SECURE_COOKIE
              value: "false"
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: N8N_POSTGRES_NON_ROOT_USER
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: N8N_POSTGRES_NON_ROOT_PASSWORD
            - name: N8N_PATH
              value: /n8n/
            - name: N8N_PROTOCOL
              value: https
            - name: N8N_HOST
              value: infra.aipixell.com
            - name: N8N_PORT
              value: "5678"
          image: n8nio/n8n
          name: n8n
          ports:
            - containerPort: 5678
          resources:
            requests:
              memory: "250Mi"
            limits:
              memory: "500Mi"
          volumeMounts:
            - mountPath: /data
              name: n8n-pv
              subPath: n8n
      restartPolicy: Always
      volumes:
        - name: n8n-pv
          persistentVolumeClaim:
            claimName: n8n-pvc
        - name: n8n-secret
          secret:
            secretName: n8n-secret
        - name: infra-secrets
          secret:
            secretName: infra-secrets