# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   labels:
#     service: n8n-claim0
#   name: n8n-claim0
#   namespace: infra
# spec:
#   storageClassName: efs-n8n
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 10Gi
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
  namespace: infra
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi