apiVersion: v1
kind: Service
metadata:
  name: n8n-svc
  namespace: infra
spec:
  type: NodePort 
  ports:
    - name: "5678"
      port: 5678
      targetPort: 5678
      protocol: TCP
  selector:
    app: n8n