apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: ${ray_cluster_name}
  namespace: ${namespace}
spec:
  rayVersion: ${ray_version}
  enableInTreeAutoscaling: true
  autoscalerOptions:
    upscalingMode: Default
    idleTimeoutSeconds: ${ray_autoscaler_idle_timeout_seconds}
    imagePullPolicy: IfNotPresent
    # Optionally specify the Autoscaler container's securityContext.
    securityContext: {}
    env: []
    envFrom: []
    resources:
      limits:
        cpu: ${ray_autoscaler_cpu_use}
        memory: ${ray_autoscaler_ram_use}
      requests:
        cpu: ${ray_autoscaler_cpu_use}
        memory: ${ray_autoscaler_ram_use}
  # Ray head pod template
  headGroupSpec:
    rayStartParams:
      # Setting "num-cpus: 0" to avoid any Ray actors or tasks being scheduled on the Ray head Pod.
      num-cpus: "0"
    # Pod template
    template:
      spec:
        containers:
        # The Ray head container
        - name: ray-head
          image: ${ray_runtime_cpu}
          ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          resources:
            limits:
              cpu: ${ray_head_cpu_use}
              memory: ${ray_head_ram_use}
            requests:
              cpu: ${ray_head_cpu_use}
              memory: ${ray_head_ram_use}
          env:
            - name: RAY_DEDUP_LOGS
              value: "0"
            - name: RAY_enable_autoscaler_v2 # Pass env var for the autoscaler v2.
              value: "1"
        restartPolicy: Never # No restart to avoid reuse of pod for different ray nodes.
  workerGroupSpecs:
  # the Pod replicas in this group typed worker
  - replicas: 0
    minReplicas: ${ray_cpuworker_replica_min}
    maxReplicas: ${ray_cpuworker_replica_max}
    groupName: cpu-group
    rayStartParams: {}
    # Pod template
    template:
      spec:
        containers:
        - name: ray-worker-cpu
          image: ${ray_runtime_cpu}
          resources:
            limits:
              cpu: ${ray_cpuworker_cpu_use}
              memory: ${ray_cpuworker_ram_use}
            requests:
              cpu: ${ray_cpuworker_cpu_use}
              memory: ${ray_cpuworker_ram_use}
        restartPolicy: Never # Never restart a pod to avoid pod reuse
      
  - replicas: 0
    minReplicas: ${ray_gpuworker_replica_min}
    maxReplicas: ${ray_gpuworker_replica_max}
    groupName: gpu-group
    rayStartParams: {}
    # Pod template
    template:
      spec:
        containers:
        - name: ray-worker-gpu
          image: ${ray_runtime_gpu}
          resources:
            limits:
              cpu: ${ray_gpuworker_cpu_use}
              memory: ${ray_gpuworker_ram_use}
              nvidia.com/gpu: ${ray_gpuworker_gpu_use}
            requests:
              cpu: ${ray_gpuworker_cpu_use}
              memory: ${ray_gpuworker_ram_use}
              nvidia.com/gpu: ${ray_gpuworker_gpu_use}
        tolerations:
          - key: nvidia.com/gpu
            operator: "Exists"
            effect: "NoSchedule"
        restartPolicy: Never # Never restart a pod to avoid pod reuse
