apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-influx-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: efs.csi.aws.com
parameters:
  fileSystemId: "${efs_id}" # Terraform으로 생성된 EFS ID를 사용
  provisioningMode: efs-ap
  directoryPerms: "777"
  uid: "1000"
  gid: "1000" 