apiVersion: v1
kind: Service
metadata:
  name: raycluster-head-nlb
  namespace: ray
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: "prod-ray-nlb" # NLB 이름 지정
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Environment=prod"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-0233b8303c55c3a8a,sg-03084b1063a9f9971,sg-076d8d3c946765510"          # 빈 값은 보안 그룹을 동적으로 생성
    service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"                 # NLB 사용
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing" 
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance" # Instance Target 사용
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "TCP" # 헬스체크 프로토콜
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "traffic-port"   # Pod의 컨테이너 포트 (Dashboard)
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "20" # 헬스체크 주기(초)
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"   # 헬스체크 타임아웃(초)
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-threshold-count: "3" # 성공 임계치
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold-count: "3" # 실패 임계치
  labels:
    app: raycluster
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: dashboard
      port: 80           # 외부에서 접근할 포트
      targetPort: 8265     # Pod의 컨테이너 포트
      protocol: TCP
    - name: metrics
      port: 8080           # 외부에서 접근할 포트
      targetPort: 8080     # Pod의 컨테이너 포트
      protocol: TCP
    - name: client
      port: 10001          # 외부에서 접근할 포트
      targetPort: 10001    # Pod의 컨테이너 포트
      protocol: TCP
  selector:
    app.kubernetes.io/created-by: kuberay-operator
    app.kubernetes.io/name: kuberay
    ray.io/cluster: raycluster
    ray.io/identifier: raycluster-head
    ray.io/node-type: head