apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  fileSystemId: "${efs_id}" # Terraform으로 생성된 EFS ID를 사용
  directoryPerms: "777"
  provisioningMode: efs-ap