
name: Deploy Docker Compose[redis]

on:
  push:
    paths:
      - 'redis/docker-compose.yaml'
      - '.github/workflows/deploy-redis.yml'
  workflow_dispatch:
env: 
  COMPOSE_PATH: redis/docker-compose.yaml
  ENV_PATH: redis/.env
jobs:
  deploy:
    runs-on: [self-hosted, base]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file from secrets
      run: |
        echo "${{ vars.REDIS_ACCESS_INFOS }}" > ${{ env.ENV_PATH }}
        echo "${{ vars.REDIS_LOGIN_INFOS }}" >> ${{ env.ENV_PATH }}
        echo "${{ vars.REDIS_ETCS }}" >> ${{ env.ENV_PATH }}

    - name: Deploy Docker Compose
      run: |
        docker compose -f ${{ env.COMPOSE_PATH }} down
        docker compose -f ${{ env.COMPOSE_PATH }} -p ${{ vars.DOCKER_COMPOSE_PROJECT_NAME }} --env-file=${{ env.ENV_PATH }} up -d
